### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by NoobFullStack** [dribia/drifactorial#5]
## Expected Behavior

To push the Authorization Code via the obtain_access_token function and receive the access_token.

## Current Behavior

Currently I am receiving the authorization code, but unable to get the access_token

## Steps to Reproduce

1. Open new project -> pip install drifactorial
2. Following the guide: https://dribia.github.io/drifactorial/usage/authorization/
3. Up tot "Authorize your user for using the application" goes well
4. When I enter: 
`token = dummy_factorial.obtain_access_token(
    client_id=client_id,
    client_secret=client_secret,
    redirect_uri=redirect_uri,
    authorization_key=authorization_key,
)`

I recieve the following errors: 
`>>> token = dummy_factorial.obtain_access_token(
...     client_id=client_id,
...     client_secret=client_secret,
...     redirect_uri=redirect_uri,
...     authorization_key=authorization_key,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\CND127KONB\PycharmProjects\pythonProject\venv\lib\site-packages\drifactorial\__init__.py", line 379, in obtain_access_token
    response = self._post_token(data=data)
  File "C:\Users\CND127KONB\PycharmProjects\pythonProject\venv\lib\site-packages\drifactorial\__init__.py", line 360, in _post_token
    response = request.urlopen(request_url)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request`

1) I have tried putting in the client_id, client_secret, redirect_uri and authorization_key manually by hand, so to make sure they match.. 
2) Looking into the drifactorial -> __init__.py file, hovering over the variables named at step 1, they do not visualize the variable values..

**Comment by DavidIsermann** [comment]
I also have issues with getting access_token. I get this error message "certificate verify failed: unable to get local issuer certificate".
